spring:
  profiles:
    active: dev

---

server:
  port: 6001
spring:
  profiles: dev
  application:
    name: microservice-config-eureka
eureka:
  instance:
    hostname: 192.168.10.11
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  server:
    enable-self-preservation: false

---

server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-config-eureka  
eureka:
  instance:
    hostname: 192.168.10.11
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  server:
    enable-self-preservation: true
